import { db } from '../firebase/firebaseConfig.js';
import { setDoc, doc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.3/firebase-firestore.js";

// Array of icons
const icons = [
    'fas fa-user',
    'fas fa-home',
    'fas fa-car',
    'fas fa-cog',
    'fas fa-bell',
    'fas fa-briefcase',
    'fas fa-chart-line',
    'fas fa-file-alt',
    'fas fa-piggy-bank',
    'fas fa-wallet',
    'fas fa-handshake',
    'fas fa-globe',
    'fas fa-heart',
    'fas fa-users',
    'fas fa-user-friends',
    'fas fa-user-tie',
    'fas fa-id-badge',
    'fas fa-id-card',
    'fas fa-calendar-alt',
    'fas fa-clock',
    'fas fa-dollar-sign',
    'fas fa-credit-card',
    'fas fa-money-bill-wave',
    'fas fa-gift',
    'fas fa-graduation-cap',
    'fas fa-laptop',
    'fas fa-headset',
    'fas fa-umbrella',
    'fas fa-hospital',
    'fas fa-stethoscope',
    'fas fa-apple-alt',
    'fas fa-leaf',
    'fas fa-coffee',
    'fas fa-apple',
    'fas fa-basketball-ball',
    'fas fa-futbol',
    'fas fa-swimmer',
    'fas fa-dumbbell',
    'fas fa-biking',
    'fas fa-yoga',
    'fas fa-mountain',
    'fas fa-hand-holding-heart',
    'fas fa-user-md',
    'fas fa-medkit',
    'fas fa-pills',
    'fas fa-first-aid',
    'fas fa-hands-helping',
    'fas fa-briefcase-medical',
    'fas fa-wheelchair',
    'fas fa-blind',
    'fas fa-deaf',
    'fas fa-sign-language',
    'fas fa-chalkboard-teacher',
    'fas fa-user-graduate',
    'fas fa-school',
    'fas fa-university',
    'fas fa-building',
    'fas fa-city',
    'fas fa-hands',
    'fas fa-hand-holding',
    'fas fa-hand-sparkles',
    'fas fa-hand-paper',
    'fas fa-hand-peace',
    'fas fa-hand-point-up',
    'fas fa-hand-point-down',
    'fas fa-hand-point-left',
    'fas fa-hand-point-right',
    'fas fa-handshake-alt',
    'fas fa-pray',
    'fas fa-running',
    'fas fa-walking',
    'fas fa-jogging',
    'fas fa-clinic-medical',
    'fas fa-hospital-alt',
    'fas fa-file-medical',
    'fas fa-notes-medical',
    'fas fa-heartbeat',
    'fas fa-procedures',
    'fas fa-syringe',
    'fas fa-tablets',
    'fas fa-band-aid',
    'fas fa-hospital-user',
    'fas fa-user-nurse',
    'fas fa-prescription-bottle',
    'fas fa-prescription-bottle-alt',
    'fas fa-user-plus',
    'fas fa-user-minus',
    'fas fa-user-clock',
    'fas fa-user-check',
    'fas fa-user-slash',
    'fas fa-users-cog',
    'fas fa-user-shield',
    'fas fa-comments',
    'fas fa-comment-dots',
    'fas fa-comment-medical',
    'fas fa-comment-dollar',
    'fas fa-comment-alt',
    'fas fa-comments-alt',
    'fas fa-smile',
    'fas fa-frown',
    'fas fa-meh',
    'fas fa-smile-beam',
    'fas fa-smile-wink',
    'fas fa-sad-tear',
    'fas fa-sad-cry',
    'fas fa-laugh',
    'fas fa-laugh-beam',
    'fas fa-laugh-squint',
    'fas fa-laugh-wink',
    'fas fa-dizzy',
    'fas fa-flushed',
    'fas fa-grin',
    'fas fa-grin-alt',
    'fas fa-grin-beam',
    'fas fa-grin-beam-sweat',
    'fas fa-grin-hearts',
    'fas fa-grin-squint',
    'fas fa-grin-squint-tears',
    'fas fa-grin-stars',
    'fas fa-grin-tears',
    'fas fa-grin-tongue',
    'fas fa-grin-tongue-squint',
    'fas fa-grin-tongue-wink',
    'fas fa-grin-wink',
    'fas fa-user-circle',
    'fas fa-users',
    'fas fa-user-friends',
    'fas fa-user-tie',
    'fas fa-id-badge',
    'fas fa-id-card',
    'fas fa-calendar-alt',
    'fas fa-clock',
    'fas fa-dollar-sign',
    'fas fa-money-bill-wave',
    'fas fa-briefcase',
    'fas fa-chart-line',
    'fas fa-file-alt',
    'fas fa-book',
    'fas fa-clipboard',
    'fas fa-award',
    'fas fa-certificate',
    'fas fa-star',
    'fas fa-rocket',
    'fas fa-lightbulb',
    'fas fa-shield-alt',
    'fas fa-lock',
    'fas fa-key',
    'fas fa-medal',
    'fas fa-trophy',
    'fas fa-piggy-bank',
    'fas fa-wallet',
    'fas fa-coins',
    'fas fa-hand-holding-usd',
    'fas fa-percent',
    'fas fa-gift',
    'fas fa-shopping-cart',
    'fas fa-truck',
    'fas fa-plane',
    'fas fa-globe',
    'fas fa-map-marked-alt',
    'fas fa-laptop',
    'fas fa-tablet-alt',
    'fas fa-mobile-alt',
    'fas fa-headset',
    'fas fa-umbrella',
    'fas fa-heart',
    'fas fa-heartbeat',
    'fas fa-band-aid',
    'fas fa-pills',
    'fas fa-syringe',
    'fas fa-hospital',
    'fas fa-stethoscope',
    'fas fa-ambulance',
    'fas fa-clinic-medical',
    'fas fa-file-medical',
    'fas fa-notes-medical',
    'fas fa-user-md',
    'fas fa-tooth',
    'fas fa-brain',
    'fas fa-microscope',
    'fas fa-balance-scale',
    'fas fa-graduation-cap',
    'fas fa-book-open',
    'fas fa-pencil-alt',
    'fas fa-eraser',
    'fas fa-comments',
    'fas fa-comment-dots',
    'fas fa-comment-medical',
    'fas fa-phone',
    'fas fa-envelope',
    'fas fa-map-pin',
    'fas fa-home',
    'fas fa-building',
    'fas fa-store-alt',
    'fas fa-landmark',
    'fas fa-city',
    'fas fa-train',
    'fas fa-bus',
    'fas fa-car',
    'fas fa-motorcycle',
    'fas fa-bicycle',
    'fas fa-walking',
    'fas fa-running',
    'fas fa-swimmer',
    'fas fa-skiing',
    'fas fa-football-ball',
    'fas fa-basketball-ball',
    'fas fa-baseball-ball',
    'fas fa-golf-ball',
    'fas fa-volleyball-ball',
    'fas fa-futbol',
    'fas fa-dumbbell',
    'fas fa-biking',
    'fas fa-yoga',
    'fas fa-paw',
    'fas fa-kiwi-bird',
    'fas fa-tree',
    'fas fa-seedling',
    'fas fa-cloud',
    'fas fa-sun',
    'fas fa-moon',
    'fas fa-snowflake',
    'fas fa-fire',
    'fas fa-thermometer',
    'fas fa-tint',
    'fas fa-wind',
    'fas fa-water',
    'fas fa-wine-glass',
    'fas fa-beer',
    'fas fa-cocktail',
    'fas fa-coffee',
    'fas fa-utensils',
    'fas fa-pizza-slice',
    'fas fa-birthday-cake'
];

// Function to save icons to Firestore
const saveIconsToFirestore = async () => {
  try {
    const iconsRef = doc(db, 'icons', 'iconList');
    await setDoc(iconsRef, { icons });
    alert('Icons saved successfully!');
  } catch (e) {
    console.error('Error saving icons: ', e);
    alert('Error saving icons. Please try again.');
  }
};

// Function to retrieve icons from Firestore
const retrieveIconsFromFirestore = async () => {
  try {
    const iconsRef = doc(db, 'icons', 'iconList');
    const docSnap = await getDoc(iconsRef);

    if (docSnap.exists()) {
      const iconsData = docSnap.data().icons;
      displayIcons(iconsData);
    } else {
      console.log('No such document!');
    }
  } catch (e) {
    console.error('Error retrieving icons: ', e);
  }
};

// Function to display icons on the page
const displayIcons = (icons) => {
  const iconsContainer = document.getElementById('icons-container');
  iconsContainer.innerHTML = ''; // Clear previous icons

  icons.forEach(icon => {
    const iconElement = document.createElement('i');
    iconElement.className = icon;
    iconsContainer.appendChild(iconElement);
  });
};

// Attach event listener to the save button
document.getElementById('save-icons').addEventListener('click', saveIconsToFirestore);

// Retrieve and display icons on page load
retrieveIconsFromFirestore();
